version: '3.6'
services:
    database:
        #
        # MariaDB database
        #
        # ${PWD##*/}
        #
        container_name: ${STACKNAME}_database
        image: mariadb:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - databasedata:/var/lib/mysql
            - $PWD:/backup
        networks:
          - internal
    memcached:
        #
        # Memchache server 
        #
        image: memcached:latest
        container_name: ${STACKNAME}_memcached
        restart: always
        depends_on:
          - database
        networks:
          - internal
    web:
        #
        # Apache webserver prepared for php-fpm
        #
        image: prestashop/prestashop:1.7-7.2-apache
        container_name: ${STACKNAME}_web
        restart: always
        environment:
            - "DB_SERVER=${DB_SERVER:-database}"
            - "DB_USER=${DB_USER}"
            - "DB_PASSWD=${DB_PASSWORD}"
            - "DB_PREFIX=${DB_PREFIX:-ps_}"
            - "DB_NAME=${DB_NAME:-prestashop}"
            - "PS_DEV_MODE=${PS_DEV_MODE:-0}"
            - "PS_HOST_MODE=${PS_HOST_MODE:-0}"
            - "PS_DEMO_MODE=${PS_DEMO_MODE:-0}"
            - "PS_INSTALL_AUTO=${PS_INSTALL_AUTO:-0}"
            - "PS_ERASE_DB=${PS_DB_ERASE:-0}"
            - "PS_INSTALL_DB=${PS_INSTALL_DB:-0}"
            - "PS_LANGUAGE=${SHOP_LANGUAGE:-nl}"
            - "PS_COUNTRY=${SHOP_COUNTRY:-nl}"
            - "PS_ALL_LANGUAGES=${PS_ALL_LANGUAGES:-0}"
            - "PS_FOLDER_ADMIN=admin"
            - "PS_FOLDER_INSTALL=install"
            - "PS_ENABLE_SSL=${PS_ENABLE_SSL}"
            - "ADMIN_MAIL=${ADMIN_MAIL}"
            - "ADMIN_PASSWD=${ADMIN_PASSWD}"
            - "PS_HANDLE_DYNAMIC_DOMAIN=${PS_HANDLE_DYNAMIC_DOMAIN}"
        labels:
             - traefik.enable=${TRAEFIK_ENABLE}
             - traefik.http.routers.${STACKNAME}_webu.rule=Host(`${PS_HANDLE_DYNAMIC_DOMAIN}`)             
             - traefik.http.routers.${STACKNAME}_webu.entrypoints=http
             - traefik.http.routers.${STACKNAME}_webu.middlewares=${STACKNAME}-redirectscheme
             - traefik.http.middlewares.${STACKNAME}-redirectscheme.redirectscheme.scheme=https
             - traefik.http.middlewares.${STACKNAME}-redirectscheme.redirectscheme.permanent=true
             - traefik.http.routers.${STACKNAME}_web.entrypoints=https
             - traefik.http.routers.${STACKNAME}_web.rule=Host(`${PS_HANDLE_DYNAMIC_DOMAIN}`)
             - traefik.http.routers.${STACKNAME}_web.service=${STACKNAME}_web@docker
             - traefik.http.services.${STACKNAME}_web.loadbalancer.server.port=80
             - traefik.docker.network=proxy
             - traefik.http.routers.${STACKNAME}_web.tls=true
             - traefik.http.routers.${STACKNAME}_web.tls.certresolver=http
             - traefik.http.routers.${STACKNAME}_web.tls.domains[0].main=${PS_HANDLE_DYNAMIC_DOMAIN}
             - traefik.http.routers.${STACKNAME}_web.tls.options=default
        links:
          - database:database
        depends_on:
          - database
          - memcached
        volumes:
            - filesystemdata:/var/www/html
            - $PWD:/backup
        #ports:
        #  - 8089:80
        networks:
          - proxy
          - internal
    scheduler:
        #
        # https://github.com/mcuadros/ofelia
        #
        image: mcuadros/ofelia:latest
        container_name: ${STACKNAME}_scheduler
        networks:
          - internal
        depends_on:
            - web
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        #labels:
        #    ofelia.job-local.my-test-job.schedule: "@every 65s"
        #    ofelia.job-local.my-test-job.command: "date"    
volumes:
  filesystemdata:
     name: ${STACKNAME}_data
  databasedata:
     name: ${STACKNAME}_database
networks:
  proxy:
    external: true
  internal:
    name: ${STACKNAME}_network
      


