version: '3'
services:
    web:
        image: jerryhopper/apache2-fpm:latest
        container_name: prestashop_web
        restart: always
        environment:
            - "VIRTUAL_HOST=my.domain.ext"
            - "APACHE_DOCUMENTROOT=/app/web"
        links:
            - php
        depends_on:
            - php
        volumes:
            - ./app:/app:cached
        ports:
            - 8089:80
    database:
        container_name: prestashop_database
        image: mariadb:latest
        restart: always
    php:
        image: jerryhopper/phpfpm:latest
        container_name: prestashop_php
        restart: always
        volumes:
            - ./app:/app:cached
        environment:
            - "PHP_SESSION_SAVE_HANDLER=redis"
            - "PHP_SESSION_SAVE_PATH=tcp://redis:6379"
            - "PHP_MAX_EXECUTION_TIME=120"
            - "PHP_OPCACHE_LIMIT=64M"
            - "PHP_OPCACHE_REVALIDATE=2"
            - "PHP_SMTP_HOST=localhost"
        links:
            - redis
        depends_on:
            - redis
    redis:
        image: redis:4-alpine
        container_name: prestashop_redis
        restart: always
    memcached:
        image: memcached:latest
        container_name: prestashop_memcached
        restart: always
