version: '3'
services:
    web:
        #
        # Apache webserver prepared for php-fpm
        #
        image: jerryhopper/apache2-fpm:latest
        container_name: prestashop_web
        restart: always
        environment:
            - "VIRTUAL_HOST=my.domain.ext"
            - "APACHE_DOCUMENTROOT=/app/web"
        links:
            - php
        depends_on:
            - php
        volumes:
            - prestashop-data:/app:cached
        ports:
            - 8089:80
    database:
        #
        # MariaDB database
        #
        container_name: prestashop_database
        image: mariadb:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=test123
    php:
        #
        # php-fpm binary
        #
        image: jerryhopper/phpfpm:latest
        container_name: prestashop_php
        restart: always
        depends_on:
            - redis
        # Scheduler!
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.datecron.schedule: "@every 60s"
            ofelia.job-exec.datecron.command: "uname -a"
        volumes:
            - prestashop-data:/app:cached
        environment:
            - "PHP_SESSION_SAVE_HANDLER=redis"
            - "PHP_SESSION_SAVE_PATH=tcp://redis:6379"
            - "PHP_MAX_EXECUTION_TIME=120"
            - "PHP_OPCACHE_LIMIT=64M"
            - "PHP_OPCACHE_REVALIDATE=2"
            - "PHP_SMTP_HOST=localhost"
        links:
            - redis
        depends_on:
            - database
    redis:
        # 
        # Redis for session storage
        #
        image: redis:4-alpine
        container_name: prestashop_redis
        restart: always
        depends_on: 
            - memcached
    memcached:
        #
        # Memchache server 
        #
        image: memcached:latest
        container_name: prestashop_memcached
        restart: always
    scheduler:
        #
        # https://github.com/mcuadros/ofelia
        #
        image: mcuadros/ofelia:latest
        depends_on:
            - php
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            ofelia.job-local.my-test-job.schedule: "@every 65s"
            ofelia.job-local.my-test-job.command: "date"    
volumes:
  prestashop-data:

