version: '3'
services:
    web:
        image: jerryhopper/apache2-fpm:latest
        restart: always
        environment:
            - "VIRTUAL_HOST=my.domain.ext"
            - "APACHE_DOCUMENTROOT=/app/web"
        links:
            - php
        depends_on:
            - php
        volumes:
            - .:/app:cached
    php:
        image: jerryhopper/phpfpm:latest
        restart: always
        volumes:
            - .:/app:cached
        environment:
            - "PHP_SESSION_SAVE_HANDLER=redis"
            - "PHP_SESSION_SAVE_PATH=tcp://redis:6379"
            - "PHP_MAX_EXECUTION_TIME=120"
            - "PHP_MEMORY_LIMIT=256M"
            - "PHP_UPLOAD_LIMIT=8M"
            - "PHP_OPCACHE_LIMIT=64M"
            - "PHP_OPCACHE_REVALIDATE=2"
            - "PHP_SMTP_HOST=localhost"
            - "PHP_MAX_INPUT_VARS=1000"
        links:
            - redis
        depends_on:
            - redis
    redis:
        image: redis:4-alpine
        restart: always
    memcached:
        image: memcached:latest
        restart: always
