version: '3'
services:
    web2:
        #
        #
        #
        image: prestashop/prestashop:1.7.7.1-fpm
        container_name: prestashop_web2
        restart: always
        ports:
            - 8085:80
        environment:
            - PS_DEV_MODE=false
            #- PS_HOST_MODE=true
            #- DB_SERVER=database
            #- DB_USER=prestashop
            #- DB_PASSWD=webturd123
            #- DB_NAME=prestashop
            #- PS_LANGUAGE=nl
            #- PS_HANDLE_DYNAMIC_DOMAIN=1
        #volumes:
        #    - prestashop-data:/var/www/html
    database:
        #
        # MariaDB database
        #
        container_name: prestashop_database
        image: mariadb:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - prestashop-database:/var/lib/mysql
    redis:
        # 
        # Redis for session storage
        #
        image: redis:4-alpine
        container_name: prestashop_redis
        restart: always
        depends_on: 
            - memcached
    memcached:
        #
        # Memchache server 
        #
        image: memcached:latest
        container_name: prestashop_memcached
        restart: always
    scheduler:
        #
        # https://github.com/mcuadros/ofelia
        #
        image: mcuadros/ofelia:latest
        container_name: prestashop_scheduler
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        #labels:
        #    ofelia.job-local.my-test-job.schedule: "@every 65s"
        #    ofelia.job-local.my-test-job.command: "date"    
volumes:
  prestashop-data:
  prestashop-database:

