version: '3'
services:
    web:
        image: jerryhopper/apache2-fpm:latest
        restart: always
        environment:
            - "VIRTUAL_HOST=my.domain.ext"
            - "APACHE_DOCUMENTROOT=/app/web"
        volumes:
            - .:/app:cached
